site_name: TestNG Docs

repo_url: https://github.com/yatheeshraju/testng-docs

theme: 'material'

markdown_extensions:
    - codehilite
    - admonition
    - toc:
        permalink: true
    - pymdownx.snippets:
        base_path: docs

nav:
    - 'Welcome' : 'index.md'
    - 'Introduction' : 'basic.md'
    - 'Getting Started': 'gettingstarted.md'
    - 'Download' : 'download.md'
    - 'Migrating from JUnit' : 'migratingfromjunit.md'
    - 'Annotations' : 'annotations.md'
    - 'Test methods, classes and groups' : 'testhelpers.md'
    - 'Run TestNG': 'runningtestng.md'
    - 'TestNG XML': 'testngxml.md'
    - 'Test Results' : 'testresults.md' 
    - 'YAML' : 'yaml.md'
    - 'Dry Run Your Test' : 'dryrunyourtest.md'
    -  'Ant': 'ant.md'
    - 'Maven' : 'maven.md'
    - ' Selenium ': 'selenium.md'
    - 'Eclipse' : 'eclipse.md'
    - 'Intelli JIdea' : 'idea.md'
    - 'Java Doc' : 'https://javadoc.jitpack.io/com/github/cbeust/testng/master/javadoc/' 
    - 'Book' : 'book.md'
    - 'Full Docs' : 'fulldoc.md'


copyright: 'Stylized docs of TestNG by Yatheesh Raju'

