site_name: TestNG Docs

repo_url: https://github.com/yatheeshraju/testng-docs

theme: 'material'

nav:
    - 'Welcome' : 'index.md'
    - 'Introduction' : 'basic.md'
    - 'Getting Started': 'gettingstarted.md'
    - 'Download' : 'download.md'
    - 'Test methods, classes and groups' : 'testhelpers.md'
    - 'Run TestNG': 'runningtestng.md'
    - 'TestNG XML': 'testngxml.md'
    - 'Test Results' : 'testresults.md' 
    - 'YAML' : 'yaml.md'
    - 'Dry Run Your Test' : 'dryrunyourtest.md'
    -  'Ant': 'ant.md'
    - 'Maven' : 'maven.md'
    - ' Selenium ': 'selenium.md'
    - 'Eclipse' : 'eclipse.md'
    - 'Intelli JIdea' : 'idea.md'

